#!/bin/sh -e
COMMAND="$1"
ENVIRONMENT="$2"


# verify parameters
case $COMMAND in
start|stop|restart)
	;;
*)
	echo "The command $COMMAND is not supported."
	echo "Supported commands include: start, stop, restart"
	exit
	;;
esac
case $ENVIRONMENT in
production|development)
	;;
*)
	echo "The environment $ENVIRONMENT is not supported."
	echo "Supported environments include: production, development."
	exit
	;;
esac


# check whether the pid file exists
pid_file="tmp/pids/unicorn.pid"
sock_file="tmp/sockets/unicorn.sock"
if [ -f "$pid_file" ]; then
	pid_file_exist=1
else
	pid_file_exist=0
fi
if [ -f "$sock_file" ]; then
	sock_file_exist=1
else
	sock_file_exist=0
fi

# execute the command
case $COMMAND in
start)
	if [ $pid_file_exist = 1 ]; then
		rm -rf $pid_file
	fi
	if [ $sock_file = 1 ]; then
		rm -rf $sock_file
	fi
	bundle exec unicorn_rails -c config/unicorn.rb  -D -E $ENVIRONMENT
	;;	
stop)
	if [ $pid_file_exist = 0 ]; then
		echo "Cannot find unicorn.pid at tmp/pids."
		echo "No unicorn process to stop"
		exit
	fi
	unicorn_pid=`cat tmp/pids/unicorn.pid`
	kill -9 $unicorn_pid
	;;
restart)
	if [ $pid_file_exist = 0 ]; then
		echo "Cannot find unicorn.pid at tmp/pids."
		echo "No unicorn process to stop"
	else
		unicorn_pid=`cat tmp/pids/unicorn.pid`
		kill -9 $unicorn_pid
		if [ $pid_file_exist = 1 ]; then
			rm -rf $pid_file
		fi
		if [ $sock_file = 1 ]; then
			rm -rf $sock_file
		fi
	fi
	bundle exec unicorn_rails -c config/unicorn.rb  -D -E $ENVIRONMENT
	;;
esac
