development:
  sessions:
    default:
      database: movie_development
      username: oopsdata
      password: o2psllyscdata
      hosts:
        - localhost:27017
      options:
  options:

production:
  sessions:
    default:
      # (required).
      database: movie_production
      username: oopsdata
      password: o2psllyscdata
      hosts:
        - localhost:27017
      options:
  options:
